// examples/cross-framework/vue-remote/src/routeTree.tsx
import { ref } from 'vue'
import { createRootRoute, createRoute } from '@tanstack/vue-router'

/**
 * A Vue route tree meant to be grafted into a host of another framework. Its
 * components take route data as a `data` prop instead of calling
 * `useLoaderData()`: the host mounts them as their own Vue application, which
 * puts them outside this router's match context.
 */
const items = [
  { id: 'vr-1', name: 'Vue item one' },
  { id: 'vr-2', name: 'Vue item two' },
]

let runs = 0

const rootRoute = createRootRoute({
  component: VueRemoteRoot,
  loader: () => ({ run: ++runs }),
})

function VueRemoteRoot(props: { data?: { run: number } }) {
  const clicks = ref(0)

  return (
    <section data-testid="vue-remote-root">
      <h2>Vue route tree</h2>
      <p data-testid="vue-root-loader">vue root loader #{props.data?.run}</p>
      <button
        type="button"
        data-testid="vue-root-increment"
        onClick={() => (clicks.value += 1)}
      >
        Vue state +1
      </button>
      <output data-testid="vue-root-state">{clicks.value}</output>
    </section>
  )
}

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: function VueRemoteIndex() {
    return (
      <ul data-testid="vue-remote-index">
        {items.map((item) => (
          <li key={item.id}>{item.name}</li>
        ))}
      </ul>
    )
  },
})

const detailRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/$itemId',
  loader: ({ params }) => ({
    name: items.find((item) => item.id === params.itemId)?.name ?? 'unknown',
  }),
  component: function VueRemoteDetail(props: { data?: { name: string } }) {
    return (
      <article data-testid="vue-remote-detail">
        <p data-testid="vue-detail-loader">{props.data?.name}</p>
      </article>
    )
  },
})

export const routeTree = rootRoute.addChildren([indexRoute, detailRoute])

// examples/cross-framework/solid-remote/src/routeTree.tsx
import { createSignal } from 'solid-js'
import { createRootRoute, createRoute } from '@tanstack/solid-router'

/**
 * A Solid route tree meant to be grafted into a host of another framework.
 *
 * Its components take route data as a `data` prop instead of calling
 * `useLoaderData()`. That is the one concession the cross-framework case
 * requires: the host mounts these components as their own Solid application,
 * which puts them outside this router's match context, so the framework-bound
 * hooks have nothing to read. The host reads the match and passes it across.
 */
const items = [
  { id: 'sr-1', name: 'Solid item one' },
  { id: 'sr-2', name: 'Solid item two' },
]

let runs = 0

const rootRoute = createRootRoute({
  loader: () => ({ run: ++runs }),
})

rootRoute.update({
  component: (props: { data?: { run: number } }) => {
    const [clicks, setClicks] = createSignal(0)

    return (
      <section data-testid="solid-remote-root">
        <h2>Solid route tree</h2>
        <p data-testid="solid-root-loader">
          solid root loader #{props.data?.run}
        </p>
        <button
          type="button"
          data-testid="solid-root-increment"
          onClick={() => setClicks((value) => value + 1)}
        >
          Solid state +1
        </button>
        <output data-testid="solid-root-state">{clicks()}</output>
      </section>
    )
  },
} as never)

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
})

indexRoute.update({
  component: () => (
    <ul data-testid="solid-remote-index">
      {items.map((item) => (
        <li>{item.name}</li>
      ))}
    </ul>
  ),
} as never)

const detailRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/$itemId',
  loader: ({ params }) => ({
    name: items.find((item) => item.id === params.itemId)?.name ?? 'unknown',
  }),
})

detailRoute.update({
  component: (props: { data?: { name: string } }) => (
    <article data-testid="solid-remote-detail">
      <p data-testid="solid-detail-loader">{props.data?.name}</p>
    </article>
  ),
} as never)

export const routeTree = rootRoute.addChildren([indexRoute, detailRoute])
